skilllist/skilllist/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

skilllist/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from tracker import views as tracker_views
from tracker import urls as tracker_urls


urlpatterns = [
    url(r'^$', tracker_views.home_page, name='home'),
    # prefixed with trackers/
    url(r'^trackers/', include(tracker_urls)),
    # url(r'^admin/', admin.site.urls),
]

superlist/superlist/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

tracker/urls.py
from django.conf.urls import url
from tracker import views

# omit tracker/ prefix
urlpatterns = [
    # any digits for Tracker id
    url(r'^(\d+)/$', views.view_tracker, name='view_tracker'),
    url(r'^new$', views.new_tracker, name="new_tracker"),
]

tracker/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.


class Tracker(models.Model):

    def get_absolute_url(self):
        return reverse('view_tracker', args=[self.id])


class Log(models.Model):
    text = models.TextField(blank=False)
    tracker = models.ForeignKey(Tracker, default=None)

tracker/forms.py
from django import forms
from tracker.models import Log

EMPTY_LOG_ERROR = "You can't save an empty log."


class LogForm(forms.models.ModelForm):

    class Meta:
        model = Log
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(
                attrs={
                    'placeholder': 'Enter a log.',
                    'class': 'form-control input-lg',
                }
            )
        }
        error_messages = {
            'text': {'required': EMPTY_LOG_ERROR}
        }

skilllist/lists/views.py
from django.shortcuts import render

# Create your views here.

tracker/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ValidationError
from tracker.models import Log, Tracker

# Create your views here.


def home_page(request):
    return render(request, 'home.html')


def view_tracker(request, tracker_id):
    """list Logs for a Tracker, process POST to add Log"""
    tracker = Tracker.objects.get(id=tracker_id)
    error = None

    if request.method == 'POST':
        try:
            log = Log.objects.create(text=request.POST['log_text'], tracker=tracker)
            log.full_clean()
            log.save()
            return redirect(tracker)
        except ValidationError:
            error = "You can't save an empty log."

    return render(request,
                  'tracker.html',
                  {'tracker': tracker, 'error': error})


def new_tracker(request):
    """create a new tracker and redirect to its url"""
    tracker = Tracker.objects.create()
    log = Log.objects.create(text=request.POST['log_text'],
                             tracker=tracker)
    try:
        log.full_clean()
        log.save()
    except ValidationError:
        tracker.delete()
        error = "You can't save an empty log."
        return render(request, 'home.html', {'error': error})
    return redirect(tracker)


def add_log(request, tracker_id):
    """add a new Log to an existing Tracker"""
    tracker = Tracker.objects.get(id=tracker_id)
    log = Log.objects.create(text=request.POST['log_text'],
                             tracker=tracker)
    try:
        log.full_clean()
        log.save()
    except ValidationError:
        tracker.delete()
        error = "You can't save an empty log."
        return render(request, 'home.html', {'error': error})

    return redirect(tracker)

tracker/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Skill Tracker</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">
  </head>

  <body>

    <div class="container">

      <div class="row">
        <div class="col-md-6 offset-md-3 jumbotron">
          <div class="text-center">
            <h1>{% block header_text %}{% endblock %}</h1>
            <form method="POST" action="{% block form_action %}{% endblock %}">
              <input id="id_new_log" name="log_text"
                     class="form-control input-lg"
                     placeholder="Enter a Log" />
              {% csrf_token %}
              {% if error %}
                <div class="form-group has-error">
                  <span class="help-block">{{ error }}</span>
                </div>
              {% endif %}
            </form>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6 offset-md-3">
          {% block table %}
          {% endblock %}
        </div>
      </div>

    </div>

  </body>

</html>

tracker/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new Skill Tracker{% endblock %}

{% block form_action %}{% url 'new_tracker' %}{% endblock %}

tracker/templates/tracker.html
{% extends 'base.html' %}

{% block header_text %}Your Skill Tracker{% endblock %}

{% block form_action %}{% url 'view_tracker' tracker.id %}{% endblock %}

{% block table %}
  <table id="id_log_table" class="table">
    {% for log in tracker.log_set.all %}
    <tr><td>{{ forloop.counter }}. {{ log.text }}</td></tr>
    {% endfor %}
  </table>
{% endblock %}